function status = init_model()
%INIT_MODEL Summary of this function goes here
%   Detailed explanation goes here
    d = 20;
    useLogistic = true;
    model = initModelELLA(struct('k',2,...
	    			     'd',d,...
	    			     'mu',exp(-12),...
	    			     'lambda',exp(-10),...
	    			     'ridgeTerm',exp(-5),...
	    			     'initializeWithFirstKTasks',true,...
	    			     'useLogistic',useLogistic,...
	    			     'lastFeatureIsABiasTerm',true));

    status = true
end

